//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoenniyOkrug.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class voenniy_okrugEntities : DbContext
    {
        public voenniy_okrugEntities()
            : base("name=voenniy_okrugEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mladshiy_sostav> Mladshiy_sostav { get; set; }
        public virtual DbSet<Mladshiy_zvanie> Mladshiy_zvanie { get; set; }
        public virtual DbSet<Obiedinenie> Obiedinenie { get; set; }
        public virtual DbSet<Podrazdelenie> Podrazdelenie { get; set; }
        public virtual DbSet<Sluzhashchie> Sluzhashchie { get; set; }
        public virtual DbSet<Sooruzhenie> Sooruzhenie { get; set; }
        public virtual DbSet<Specialnost> Specialnost { get; set; }
        public virtual DbSet<Starshiy_sostav> Starshiy_sostav { get; set; }
        public virtual DbSet<Starshiy_zvanie> Starshiy_zvanie { get; set; }
        public virtual DbSet<Tip_boevoy_tehniki> Tip_boevoy_tehniki { get; set; }
        public virtual DbSet<Tip_obiedineniya> Tip_obiedineniya { get; set; }
        public virtual DbSet<Tip_podrazdeleniya> Tip_podrazdeleniya { get; set; }
        public virtual DbSet<Tip_transportnoy_tehniki> Tip_transportnoy_tehniki { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Sluzhashchiy_specialnost> Sluzhashchiy_specialnost { get; set; }
        public virtual DbSet<Obiedinenie_chast> Obiedinenie_chast { get; set; }
        public virtual DbSet<Boevaya_tehnika> Boevaya_tehnika { get; set; }
        public virtual DbSet<Transportnaya_tehnika> Transportnaya_tehnika { get; set; }
    }
}
