//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoenniyOkrug.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podrazdelenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podrazdelenie()
        {
            this.Podrazdelenie1 = new HashSet<Podrazdelenie>();
            this.Sooruzhenie = new HashSet<Sooruzhenie>();
            this.Obiedinenie_chast = new HashSet<Obiedinenie_chast>();
            this.Boevaya_tehnika = new HashSet<Boevaya_tehnika>();
            this.Transportnaya_tehnika = new HashSet<Transportnaya_tehnika>();
        }
    
        public int id { get; set; }
        public Nullable<int> tip { get; set; }
        public string nazvanie { get; set; }
        public Nullable<int> id_starshego { get; set; }
        public Nullable<int> komandir { get; set; }
        public string location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podrazdelenie> Podrazdelenie1 { get; set; }
        public virtual Podrazdelenie Podrazdelenie2 { get; set; }
        public virtual Sluzhashchie Sluzhashchie { get; set; }
        public virtual Tip_podrazdeleniya Tip_podrazdeleniya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sooruzhenie> Sooruzhenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obiedinenie_chast> Obiedinenie_chast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boevaya_tehnika> Boevaya_tehnika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transportnaya_tehnika> Transportnaya_tehnika { get; set; }
    }
}
