//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoenniyOkrug.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sluzhashchiy_specialnost
    {
        public int id { get; set; }
        public Nullable<int> sluzhashchiy { get; set; }
        public Nullable<int> specialnost { get; set; }
    
        public virtual Sluzhashchie Sluzhashchie { get; set; }
        public virtual Specialnost Specialnost1 { get; set; }
    }
}
