//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoenniyOkrug.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sluzhashchie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sluzhashchie()
        {
            this.Podrazdelenie = new HashSet<Podrazdelenie>();
            this.Sluzhashchie1 = new HashSet<Sluzhashchie>();
            this.Sluzhashchiy_specialnost = new HashSet<Sluzhashchiy_specialnost>();
        }
    
        public int id { get; set; }
        public string imya { get; set; }
        public string otchestvo { get; set; }
        public string familiya { get; set; }
        public Nullable<int> id_starshego { get; set; }
    
        public virtual Mladshiy_sostav Mladshiy_sostav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podrazdelenie> Podrazdelenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sluzhashchie> Sluzhashchie1 { get; set; }
        public virtual Sluzhashchie Sluzhashchie2 { get; set; }
        public virtual Starshiy_sostav Starshiy_sostav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sluzhashchiy_specialnost> Sluzhashchiy_specialnost { get; set; }
    }
}
