//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoenniyOkrug.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Starshiy_sostav
    {
        public int id { get; set; }
        public Nullable<int> zvanie { get; set; }
        public string dop_info { get; set; }
    
        public virtual Sluzhashchie Sluzhashchie { get; set; }
        public virtual Starshiy_zvanie Starshiy_zvanie { get; set; }
    }
}
