//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoenniyOkrug.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip_boevoy_tehniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tip_boevoy_tehniki()
        {
            this.Boevaya_tehnika = new HashSet<Boevaya_tehnika>();
        }
    
        public int id { get; set; }
        public string nazvanie { get; set; }
        public string dop_info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boevaya_tehnika> Boevaya_tehnika { get; set; }
    }
}
